# Setup
title:               SOL UNIV
tagline:             ''
description:         'SOLANA UNIVERSE and/or UNIVERSITY'
url:                 "https://sa-iy-ou.github.io"
baseurl:             "/soluniv"
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              ''
  url:               ''
  email:             ''

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom vars
version:             1.1.0
google_analytics_id: 
